consumes:
- application/json
definitions:
  handler.ErrorResponseModel:
    properties:
      error:
        example: Error Message
        type: string
    type: object
  handler.SuccessResponseModel:
    properties:
      message:
        example: Success Message
        type: string
    type: object
  models_book.BookFilterResponse:
    properties:
      _id:
        type: string
      author:
        type: string
      borrowed_count:
        type: integer
      categories:
        items:
          type: string
        type: array
      is_borrow:
        type: boolean
      title:
        type: string
    type: object
  models_lotto.Lotto:
    properties:
      back_three_digit_prize:
        example:
        - '[''376'''
        - ' ''297'']'
        items:
          type: string
        type: array
      back_two_digit_prize:
        example: "51"
        type: string
      date:
        example: "2025-01-01T00:00:00Z"
        type: string
      first_prize:
        example: "730209"
        type: string
      front_three_digit_prize:
        example:
        - '[''446'''
        - ' ''065'']'
        items:
          type: string
        type: array
    type: object
  models_movie.MovieRes:
    properties:
      adult:
        type: boolean
      description:
        type: string
      genres:
        items:
          type: integer
        type: array
      id:
        type: string
      rating:
        type: number
      title:
        type: string
    type: object
  services_book.responseBook:
    properties:
      data:
        $ref: '#/definitions/models_book.BookFilterResponse'
    type: object
  services_book.responseBookList:
    properties:
      data:
        items:
          $ref: '#/definitions/models_book.BookFilterResponse'
        type: array
    type: object
  services_lotto.responseLotto:
    properties:
      data:
        $ref: '#/definitions/models_lotto.Lotto'
    type: object
  services_lotto.responseLottoList:
    properties:
      data:
        items:
          $ref: '#/definitions/models_lotto.Lotto'
        type: array
    type: object
  services_movie.responseMovie:
    properties:
      data:
        $ref: '#/definitions/models_movie.MovieRes'
    type: object
  services_movie.responseMovieList:
    properties:
      data:
        items:
          $ref: '#/definitions/models_movie.MovieRes'
        type: array
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a API Swagger documentation included book, movie and lotto
    API.
  termsOfService: The Terms of Service for the API http://swagger.io/terms/.
  title: REST API using GO and Gin by TR
  version: "1.1"
paths:
  /book/list:
    get:
      consumes:
      - application/json
      description: get book list from title, author or categoyies then return as json
        message
      parameters:
      - default: The Witcher Blood of Elves
        description: string of book title
        in: query
        name: title
        type: string
      - default: Andrzej Sapkowski
        description: string of author
        in: query
        name: author
        type: string
      - collectionFormat: multi
        description: integer of categories id between 1-4
        in: query
        items:
          type: integer
        name: categories
        type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/services_book.responseBookList'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponseModel'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.ErrorResponseModel'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponseModel'
      summary: get book list by filter
      tags:
      - books
  /book/popular:
    get:
      consumes:
      - application/json
      description: find most popular book then return as json responseBook model
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/services_book.responseBook'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponseModel'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.ErrorResponseModel'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponseModel'
      summary: find most popular book
      tags:
      - books
  /borrow/book/{id}:
    put:
      consumes:
      - application/json
      description: changing isBorrow status true is mean borrowed this route will
        increase borrowed_count plus 1 then return json message
      parameters:
      - description: string id of book
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.SuccessResponseModel'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponseModel'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.ErrorResponseModel'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponseModel'
      summary: changing isBorrow status
      tags:
      - books
  /create/book/:
    post:
      consumes:
      - application/json
      description: create book by json body as models_book.BookRequest then return
        as json message
      parameters:
      - default: Some book title
        description: string of book title
        in: query
        name: title
        required: true
        type: string
      - default: my self
        description: string of book author
        in: query
        name: author
        required: true
        type: string
      - collectionFormat: multi
        description: category fill as number between 1-4
        in: query
        items:
          type: integer
        name: categories
        required: true
        type: array
      - default: false
        description: constant of borrow status true is mean borrowed
        in: query
        name: is_borrow
        required: true
        type: boolean
      - default: 0
        description: borrowed counter
        in: query
        name: borrowed_count
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.SuccessResponseModel'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponseModel'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.ErrorResponseModel'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponseModel'
      summary: create book by json body
      tags:
      - books
  /delete/book/{id}:
    delete:
      consumes:
      - application/json
      description: delete book by id then return as message
      parameters:
      - description: string id of book
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.SuccessResponseModel'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponseModel'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.ErrorResponseModel'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponseModel'
      summary: delete book by id
      tags:
      - books
  /lotto/{id}:
    get:
      consumes:
      - application/json
      description: get string by id then return lotto
      parameters:
      - description: 'Exmaple : 677accbf56ff1bc2a731b944'
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/services_lotto.responseLotto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponseModel'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.ErrorResponseModel'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponseModel'
      summary: Show an lotto
      tags:
      - lotties
  /lotto/list:
    get:
      consumes:
      - application/json
      description: get lotto list by LottoFilterReq model then return lotto list as
        json
      parameters:
      - default: "2025"
        description: year as string number
        in: query
        name: year
        type: string
      - default: "200"
        description: 3 digit of string number
        in: query
        name: b3d
        type: string
      - default: "20"
        description: 2 digit of string number
        in: query
        name: b2d
        type: string
      - default: "200"
        description: 3 digit of string number
        in: query
        name: f3d
        type: string
      - default: "730209"
        description: 6 digit of string number
        in: query
        name: first
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/services_lotto.responseLottoList'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponseModel'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.ErrorResponseModel'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponseModel'
      summary: Response lotto list by filter
      tags:
      - lotties
  /movie/{id}:
    get:
      consumes:
      - application/json
      description: get movie by id param then return movie detail as json
      parameters:
      - default: "2025"
        description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/services_movie.responseMovie'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponseModel'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.ErrorResponseModel'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponseModel'
      summary: Response movie by id
      tags:
      - movies
  /movie/list:
    get:
      consumes:
      - application/json
      description: get movie list by filter model then return movie list as json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/services_movie.responseMovieList'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponseModel'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.ErrorResponseModel'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponseModel'
      summary: Response movie list by filter
      tags:
      - movies
  /update/book/{id}:
    put:
      consumes:
      - application/json
      description: update book from param id from _id then return as json message
      parameters:
      - description: 'Example : 678139d4e150ae9affc077bf'
        in: path
        name: id
        required: true
        type: string
      - default: Some book title
        description: string of book title
        in: query
        name: title
        required: true
        type: string
      - default: my self
        description: string of book author
        in: query
        name: author
        required: true
        type: string
      - collectionFormat: multi
        description: category fill as number between 1-4
        in: query
        items:
          type: integer
        name: categories
        required: true
        type: array
      - default: false
        description: constant of borrow status true is mean borrowed
        in: query
        name: is_borrow
        required: true
        type: boolean
      - default: 0
        description: borrowed counter
        in: query
        name: borrowed_count
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.SuccessResponseModel'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponseModel'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.ErrorResponseModel'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponseModel'
      summary: update book from param id
      tags:
      - books
produces:
- application/json
schemes:
- https
- http
swagger: "2.0"
